/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

import controller.OverallControllerCallback;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author imm0022
 */
public class ExerciseDescriptionView extends javax.swing.JFrame {
    /**
     * Creates new form ExerciseDescrptionView
     */
    private OverallControllerCallback controllerCallback;
    
    public ExerciseDescriptionView(OverallControllerCallback ctl) {
        initComponents();
        controllerCallback = ctl;
        this.setSize(this.getPreferredSize());
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(true);
        fillContents();
        txtExerciseDescription.setEditable(false);
        txtExerciseDescription.setLineWrap(true);
        txtExerciseDescription.setWrapStyleWord(true);
        
        
        this.addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent windowEvent)
            {
                controllerCallback.showMainView();
            }
        });
    }
    
    private void fillContents()
    {        
        String imageFilePath = "ExerciseImages/SitUp.jpg";
        String descriptionPath = "ExerciseDescriptions/SitUp.txt";
        try {
            ImageIcon ii=new ImageIcon(
                    scaleImage(lblExercisePic.getSize().height, 
                               lblExercisePic.getSize().width, 
                               ImageIO.read(
                                    ClassLoader.getSystemResource(imageFilePath)
                                )
                    )
            );
            lblExercisePic.setIcon(ii);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        
        try(BufferedReader br = new BufferedReader(
                                    new InputStreamReader(ClassLoader.getSystemResourceAsStream(descriptionPath))
                                )
            ) 
        {
            StringBuilder sb = new StringBuilder();
            String line = br.readLine();

            while (line != null) {
                sb.append(line);
                sb.append(System.lineSeparator());
                line = br.readLine();
            }
            String everything = sb.toString();
            txtExerciseDescription.setText(everything);
        }
        catch(Exception e){
            System.out.println("bufferedReader in ExerciseDescription has crashed.... oh NOOOOOOOOOOO");
            
        }
        
    }

    private BufferedImage scaleImage(int w, int h, BufferedImage img) throws Exception {
        BufferedImage bi;
        bi = new BufferedImage(w, h, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(img, 0, 0, w, h, null);
        g2d.dispose();
        return bi;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DescriptionLabel = new javax.swing.JLabel();
        PreviousWorkOutLabel = new javax.swing.JLabel();
        PreviousSetLabel = new javax.swing.JLabel();
        PreviousRepsLabel = new javax.swing.JLabel();
        CurrentRepsLabel1 = new javax.swing.JLabel();
        CurrentSetLabel = new javax.swing.JLabel();
        PreviousWorkOutLabel1 = new javax.swing.JLabel();
        PreviousSetTextField = new javax.swing.JTextField();
        PreviousRepsTextField = new javax.swing.JTextField();
        SetsComboBox = new javax.swing.JComboBox();
        RepsComboBox = new javax.swing.JComboBox();
        UpdateWorkOutButton = new javax.swing.JButton();
        lblExercisePic = new javax.swing.JLabel();
        lblExerciseName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtExerciseDescription = new javax.swing.JTextArea();

        setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        DescriptionLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DescriptionLabel.setText("Description:");

        PreviousWorkOutLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PreviousWorkOutLabel.setText("Previous WorkOut");

        PreviousSetLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PreviousSetLabel.setText("SETS");

        PreviousRepsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PreviousRepsLabel.setText("REPS");

        CurrentRepsLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CurrentRepsLabel1.setText("REPS");

        CurrentSetLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CurrentSetLabel.setText("SETS");

        PreviousWorkOutLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PreviousWorkOutLabel1.setText("Current WorkOut");

        PreviousSetTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PreviousSetTextField.setText("3");

        PreviousRepsTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PreviousRepsTextField.setText("20");

        SetsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RepsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        UpdateWorkOutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateWorkOutButton.setText("UPDATE WORKOUT");

        lblExercisePic.setToolTipText("");

        lblExerciseName.setText("Exercise Name");

        txtExerciseDescription.setColumns(20);
        txtExerciseDescription.setRows(5);
        jScrollPane1.setViewportView(txtExerciseDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(DescriptionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblExerciseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblExercisePic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PreviousSetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PreviousSetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(341, 341, 341)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PreviousRepsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PreviousRepsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                        .addComponent(CurrentSetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(SetsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RepsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(UpdateWorkOutButton)
                                            .addComponent(PreviousWorkOutLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PreviousWorkOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(65, 65, 65)
                                        .addComponent(CurrentRepsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(135, 135, 135))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblExerciseName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblExercisePic, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreviousWorkOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreviousSetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreviousRepsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreviousSetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreviousRepsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentSetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreviousWorkOutLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentRepsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SetsComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(RepsComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateWorkOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CurrentRepsLabel1;
    private javax.swing.JLabel CurrentSetLabel;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JLabel PreviousRepsLabel;
    private javax.swing.JTextField PreviousRepsTextField;
    private javax.swing.JLabel PreviousSetLabel;
    private javax.swing.JTextField PreviousSetTextField;
    private javax.swing.JLabel PreviousWorkOutLabel;
    private javax.swing.JLabel PreviousWorkOutLabel1;
    private javax.swing.JComboBox RepsComboBox;
    private javax.swing.JComboBox SetsComboBox;
    private javax.swing.JButton UpdateWorkOutButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExerciseName;
    private javax.swing.JLabel lblExercisePic;
    private javax.swing.JTextArea txtExerciseDescription;
    // End of variables declaration//GEN-END:variables
}
